Image Preprocessing - Drawn Asset Creation etc.

https://markaicode.com/6-python-image-processing-libraries-for-advanced-visual-manipulation/

libs : openCV, skimage  and PIL

from skimage import io, filters, measure, segmentation
import matplotlib.pyplot as plt



In [1]:

from skimage import io, filters, measure, segmentation
import matplotlib.pyplot as plt

from PIL import Image, ImageFilter, ImageEnhance
import cv2
import numpy as np


import sys 
import os


print(sys.path)


['c:\\repos\\ChildrensBookRepo\\ComicGenerator\\RawPhotos\\DrawnAssets', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311\\DLLs', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311\\Lib', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311', '', 'C:\\Users\\joshc\\AppData\\Roaming\\Python\\Python311\\site-packages', 'C:\\Users\\joshc\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32', 'C:\\Users\\joshc\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32\\lib', 'C:\\Users\\joshc\\AppData\\Roaming\\Python\\Python311\\site-packages\\Pythonwin', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages']


In [4]:
filePaths = {}
directories = []
for folder,file, dir in os.walk(os.curdir):
    
    for filepath in dir:
        print(filepath)
        # directories.append(folder + f'\\{filepath}' )
        directories.append(filepath)
        
    filePaths['drawn'] = directories

blackedpixels.jpg
blackedpixels.jpg-autosave.kra
blackedpixels2.jpg
blackedpixels2.jpg-autosave.kra
haiir.jpg
hair2.jpg
hair3.jpg
ImageProcessingDrawnAssets.ipynb
IMG_20260404_212428.jpg
IMG_20260404_225055.jpg
IMG_20260404_233217.jpg
IMG_20260405_011351.jpg
IMG_20260405_231047.jpg
IMG_20260405_231051.jpg
IMG_20260405_231120.jpg
IMG_20260405_231131.jpg
IMG_20260405_231135.jpg
IMG_20260405_231140.jpg
IMG_20260405_231148.jpg
IMG_20260405_231152.jpg
IMG_20260405_231216.jpg
IMG_20260406_025406.jpg
IMG_20260406_185648.jpg
IMG_20260406_185657.jpg
IMG_20260406_185700.jpg
IMG_20260406_185703.jpg
IMG_20260406_185713.jpg
IMG_20260406_185716.jpg
IMG_20260406_185719.jpg
IMG_20260406_185727.jpg
IMG_20260406_185732.jpg
IMG_20260406_185740.jpg
IMG_20260406_185759.jpg
IMG_20260407_193441.jpg
IMG_20260407_193552.jpg
IMG_20260407_193559.jpg
IMG_20260407_193604.jpg
IMG_20260407_193609.jpg
IMG_20260407_193612.jpg
IMG_20260407_193615.jpg
IMG_20260407_194939.jpg
IMG_20260407_194942.jpg
IMG_20260407_195715.j

In [3]:
filePaths

{'drawn': ['blackedpixels.jpg',
  'blackedpixels.jpg-autosave.kra',
  'blackedpixels2.jpg',
  'blackedpixels2.jpg-autosave.kra',
  'b_tile_pixel_123_x1024_y384.jpg',
  'b_tile_pixel_38_x256_y1024.jpg',
  'b_tile_pixel_39_x256_y1152.jpg',
  'b_tile_pixel_40_x256_y1280.jpg',
  'b_tile_pixel_41_x256_y1408.jpg',
  'b_tile_pixel_47_x384_y256.jpg',
  'b_tile_pixel_48_x384_y384.jpg',
  'b_tile_pixel_49_x384_y512.jpg',
  'b_tile_pixel_53_x384_y1024.jpg',
  'b_tile_pixel_56_x384_y1408.jpg',
  'b_tile_pixel_62_x512_y256.jpg',
  'b_tile_pixel_64_x512_y512.jpg',
  'b_tile_pixel_68_x512_y1024.jpg',
  'b_tile_pixel_71_x512_y1408.jpg',
  'b_tile_pixel_77_x640_y256.jpg',
  'b_tile_pixel_79_x640_y512.jpg',
  'b_tile_pixel_95_x768_y640.jpg',
  'haiir.jpg',
  'hair2.jpg',
  'hair3.jpg',
  'ImageProcessingDrawnAssets.ipynb',
  'IMG_20260404_212428.jpg',
  'IMG_20260404_225055.jpg',
  'IMG_20260404_233217.jpg',
  'IMG_20260405_011351.jpg',
  'IMG_20260405_231047.jpg',
  'IMG_20260405_231051.jpg',
  'IMG_20

In [5]:
testImage = cv2.imread(filePaths['drawn'][6])



In [9]:
type(testImage)
testImage

gray_imagein = cv2.cvtColor(testImage, cv2.COLOR_BGR2GRAY) 

cv2.imshow('Original',gray_imagein)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [59]:
quickTest

array([[255., 255., 255., ...,   0.,   0.,   0.],
       [255., 255., 255., ...,   0.,   0.,   0.],
       [255., 255., 255., ...,   0.,   0.,   0.],
       ...,
       [255., 255., 255., ...,   0.,   0.,   0.],
       [255., 255., 255., ..., 255.,   0.,   0.],
       [255., 255., 255., ..., 255.,   0.,   0.]])

In [24]:
testImage[0:500][0:2072][0]


scalar = 255
delta = 0

# scalar = gray_imagein.max()


testImage


quickTest = np.round((gray_imagein+delta)/scalar)*255
# gray_imagein = cv2.cvtColor(testImage, cv2.COLOR_BGR2GRAY) 

cv2.imshow('Original',quickTest)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [25]:
cv2.imwrite("blackedpixels2.jpg", quickTest)

True

In [38]:
gray_imagein.shape

(4608, 2072)

In [48]:
import math

In [41]:
gray_imagein[0:500][0:2072] = 255

In [34]:
gray_imagein[0:500][0:2072][0] = 250

In [ ]:
gray_imagein.shape

(4608, 2072, 3)

In [56]:
testing_logic = (gray_imagein - (np.ones(gray_imagein.shape)*255))*-1


In [57]:
testing_logic

array([[117., 113., 111., ..., 154., 151., 152.],
       [116., 113., 112., ..., 151., 158., 151.],
       [116., 115., 115., ..., 159., 152., 154.],
       ...,
       [118., 118., 117., ..., 129., 128., 130.],
       [121., 118., 114., ..., 127., 131., 136.],
       [121., 116., 115., ..., 122., 131., 139.]])

In [ ]:
gray_imagein[0]

array([64, 62, 63, ..., 90, 92, 90], dtype=uint8)

In [6]:
cv2.imshow('Original',testImage)

In [ ]:
gray_imagein[0][0]

gray_imagein.shape

(4608, 2072)

In [ ]:
gray_imagein[0:128, 0:128]

array([[64, 62, 63, ..., 71, 71, 70],
       [64, 64, 65, ..., 73, 73, 71],
       [65, 65, 66, ..., 73, 73, 71],
       ...,
       [22, 22, 20, ..., 23, 23, 19],
       [18, 19, 19, ..., 23, 22, 21],
       [18, 19, 19, ..., 19, 20, 21]], dtype=uint8)

In [239]:
print("Image Stats")


# gray_image = gray_imagein

gray_image =quickTest

important_Stats = []
important_Stats.append(np.average(gray_image))
important_Stats.append(np.min(gray_image))
important_Stats.append(np.max(gray_image))
important_Stats.append(np.count_nonzero(gray_image))

important_Stats


# important_Stats[0] - important_Stats[1]

print(gray_image.shape[0]/128)
print(gray_image.shape[1]/128)

iteration_step = 64
chunks = []
averages = []
diffs = []
results = []
for x in range(0, int(gray_image.shape[0]/iteration_step)):
    x_run = []

    
    
    for y  in range(0, round(gray_image.shape[1]/iteration_step)):
        section = np.array(gray_image[((x)*iteration_step):(iteration_step*(x+1)), ((y)*iteration_step):iteration_step*(y+1)])
        scaled_contrast = (np.square(section / (np.ones(section.shape)*255)))*255
        contrast = abs(scaled_contrast- (np.ones(scaled_contrast.shape)*np.average(scaled_contrast)))
        
        # contrast = abs(section- (np.ones(section.shape)*np.average(section)))
        inverted =( section - (np.ones(section.shape)*255))*-1
        # averages[f'{x}_{y}'] = np.average(gray_image[((x)*iteration_step):(iteration_step*x), ((y)*iteration_step):iteration_step*y])
        chunks.append((inverted, f'{x}_{y}', section))
        averages.append(np.sum(section))
        diffs.append(np.sum(contrast))
        x_run.append(np.sum(contrast))
        
        
    results.append(x_run)
    



Image Stats
11.0390625
14.65625


In [79]:
np.array(results).shape

(11, 15)

In [240]:
window = 6

results = np.array(results)

id_groupings = []
centre = []

for x in range(0,results.shape[0]):
    for y in range(0,results.shape[1]):
        section = np.sum(results[max(x-(int(window/2)), 
                                     0):min(x+(int(window/2)), results.shape[0]), 
                                 max(0,y-(int(window/2))):min(results.shape[1],y+(int(window/2)))])
        
        id_groupings.append(section)
        
        centre.append(f'{x}_{y}')
        
        
        
    

In [241]:
id_groupings.index(np.array(id_groupings).max())

thresh2 = 0.95

interesting_groups = []

for x in id_groupings:
    if x > (np.array(id_groupings).max()*thresh2):
        interesting_groups.append((x, id_groupings.index(x)))

In [29]:
len(id_groupings)

165

In [30]:
len(interesting_groups)

2

In [242]:
for group, idx in interesting_groups:

    print(diffs.index(results[int(centre[idx].split("_")[0])][int(centre[idx].split("_")[1])]))

239
240
268
269
298


In [84]:
averages

[1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2407655,
 2407655,
 2407655,
 2407655,
 2407655,
 24076

In [243]:
averagesarray = np.array(averages)
averagesarray.max()

1044480.0

In [185]:
diffs.index(np.array(diffs).max())

53

In [244]:
interestingTiles = []

treshold = np.array(diffs).max()  - ((np.array(diffs).max() - np.array(diffs).min())*0.25)

i = 0
for x in diffs:
    if x > treshold:
        interestingTiles.append(i)
        
    i +=1

In [33]:
interestingTiles

[38, 39, 40, 41, 47, 48, 49, 53, 56, 62, 64, 68, 71, 77, 79, 95, 123]

In [34]:
len(chunks)

165

38
{'start_x': 0, 'start_y': 0, 'end_x': 0, 'end_y': 0, 'tile': False}
39
40
41
47
48
49
53
exists
exists
exists
56
exists
exists
exists
62
64
68
exists
exists
exists
exists
71
exists
exists
exists
exists
77
79
95
123


In [55]:
len(groups)

10

17

In [56]:
groups

[{'start_x': 256, 'start_y': 1024, 'end_x': 640, 'end_y': 1536},
 {'start_x': 384, 'start_y': 256, 'end_x': 768, 'end_y': 640},
 {'start_x': 384, 'start_y': 384, 'end_x': 768, 'end_y': 640},
 {'start_x': 384, 'start_y': 512, 'end_x': 768, 'end_y': 640},
 {'start_x': 512, 'start_y': 256, 'end_x': 768, 'end_y': 384},
 {'start_x': 512, 'start_y': 512, 'end_x': 768, 'end_y': 640},
 {'start_x': 640, 'start_y': 256, 'end_x': 768, 'end_y': 384},
 {'start_x': 640, 'start_y': 512, 'end_x': 768, 'end_y': 640},
 {'start_x': 768, 'start_y': 640, 'end_x': 896, 'end_y': 768},
 {'start_x': 1024, 'start_y': 384, 'end_x': 1152, 'end_y': 512}]

In [ ]:
def group_interesting_tiles(tiles, chunksin, iteration_step):
    groups = []
    
    
    group = {
        'start_x' : 0,
        'start_y' : 0,
        'end_x' : 0,
        'end_y' : 0,
        'tile' : False
    }

    
    for tile in tiles:
        new_group_flag = False
        tile_flag = True
        print(tile)
        x , y = int(chunksin[tile][1].split("_")[0])*iteration_step, int(chunksin[tile][1].split("_")[1])*iteration_step
        for collection in groups:
            if (collection['end_y'] == y and (x >= collection['start_x'] and x <= collection['end_x'])  ):
                collection['end_y'] = y +iteration_step
                tile_flag = False         
            elif (x == collection['end_x'] and y + iteration_step == collection['end_y']):
                collection['end_x'] = x + iteration_step
                tile_flag = False
            # elif  (collection['end_y'] >= y +iteration_step and collection['start_y'] <= y  
            #        and (x >= collection['start_x'] and x <= collection['end_x'])  ):
            #     print("exists")
            #     tile_flag = False
            elif  (collection['end_y'] >= y  and collection['start_y'] <= y  
                   and (x >= collection['start_x'] and x <= collection['end_x'])  ):
                print("exists")
                tile_flag = False
            
            else:
                new_group_flag = True
        
        
        if (new_group_flag and tile_flag):
                
            new_group =  {
                            'start_x' : x-iteration_step,
                            'start_y' : y-iteration_step,
                            'end_x' : x+iteration_step,
                            'end_y' :  y +iteration_step,
                        } 
            groups.append(new_group)

        if len(groups) == 0:
            new_group =  {
                                'start_x' : x-iteration_step,
                                'start_y' : y-iteration_step,
                                'end_x' : x+iteration_step,
                                'end_y' :  y +iteration_step,
                            } 
            print(group)
            groups.append(new_group)
        # print(groups)
        tile_flag == True
    for collection in groups:
        collection['end_y'] = collection['end_y'] + iteration_step
        collection['end_x'] = collection['end_x'] + iteration_step
    remove = []
    for i in range(0, len(groups)):
        for ii in range(0, len(groups)):
            if groups[i]['end_y'] >= groups[ii]['start_y'] and groups[i]['start_y'] >= groups[ii]['start_y'] and groups[i]['start_y'] <= groups[ii]['end_y'] and i != ii:
                groups[i]['end_y'] =  max(groups[i]['end_y'], groups[ii]['end_y'])
                groups[i]['start_y'] =  min(groups[i]['start_y'], groups[ii]['start_y'])
                groups[i]['end_x'] =  max(groups[i]['end_x'], groups[ii]['end_x'])
                groups[i]['start_x'] =  min(groups[i]['start_x'], groups[ii]['start_x'])
                groups[ii]['end_y'] =  max(groups[i]['end_y'], groups[ii]['end_y'])
                groups[ii]['start_y'] =  min(groups[i]['start_y'], groups[ii]['start_y'])
                groups[ii]['end_x'] =  max(groups[i]['end_x'], groups[ii]['end_x'])
                groups[ii]['start_x'] =  min(groups[i]['start_x'], groups[ii]['start_x'])
                print("overlap y")
                
            

     
    unique = []
    
    for item in groups:
        try:
            if iteration_step < 100:
                item["end_x"] = item["end_x"] + iteration_step
            unique.index(item)
        except:

            unique.append(item)
    
    
    
    
    return  unique
                
            
        # cv2.imwrite(f'b_tile_pixel_{tile}_x{x}_y{y}.jpg', chunksin[tile][2])
        
        

In [318]:
remove
for r in remove:
    print(r)
    try:
        del groups[groups.index(r)]
    except:
        print("missing")
    

{'start_x': 192, 'start_y': 1024, 'end_x': 640, 'end_y': 1600}
missing
{'start_x': 192, 'start_y': 1024, 'end_x': 640, 'end_y': 1600}
missing
{'start_x': 192, 'start_y': 1152, 'end_x': 640, 'end_y': 1600}
missing


In [378]:
groups = group_interesting_tiles(interestingTiles, chunks, iteration_step)

133
{'start_x': 0, 'start_y': 0, 'end_x': 0, 'end_y': 0, 'tile': False}
135
136
138
152
153
154
161
exists
162
163
exists
164
exists
165
166
exists
167
168
181
exists
190
exists
191
exists
196
exists
exists
exists
197
207
208
209
210
211
212
213
219
exists
220
exists
225
exists
exists
exists
226
237
exists
238
exists
241
exists
242
253
exists
exists
exists
254
exists
exists
exists
255
266
exists
267
exists
270
exists
271
278
exists
279
exists
exists
282
exists
exists
exists
283
exists
exists
exists
295
exists
296
exists
298
exists
299
exists
324
325
327
329
351
358
380
387
416
439
440
441
443
444
exists
445
468
exists
470
473
exists
exists
474
499
501
exists
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
overlap y
ove

In [323]:
remove

[{'start_x': 192, 'start_y': 1024, 'end_x': 640, 'end_y': 1600},
 {'start_x': 192, 'start_y': 1024, 'end_x': 640, 'end_y': 1600},
 {'start_x': 192, 'start_y': 1152, 'end_x': 640, 'end_y': 1600}]

In [379]:
groups

[{'start_x': 192, 'start_y': 1024, 'end_x': 704, 'end_y': 1600},
 {'start_x': 256, 'start_y': 128, 'end_x': 1280, 'end_y': 768}]

In [381]:
group = groups[0]

cv2.imshow('Original',gray_imagein[group['start_x']:group['end_x'], group['start_y']:group['end_y']])
cv2.waitKey(0)
cv2.destroyAllWindows()


In [120]:
diffs

[139061.92895507812,
 271513.609375,
 320513.4279785156,
 182629.77221679688,
 206843.4835205078,
 225956.11376953125,
 236189.47790527344,
 247959.35913085938,
 260528.8292236328,
 268275.796875,
 269938.98571777344,
 276492.8037109375,
 282933.689453125,
 285343.20178222656,
 288384.38818359375,
 287656.61767578125,
 136670.1357421875,
 252808.96020507812,
 236665.2333984375,
 367101.8984375,
 151104.640625,
 454530.24853515625,
 487105.54052734375,
 516715.875,
 540910.130859375,
 562421.2277832031,
 584343.6616210938,
 614612.4145507812,
 635841.3919677734,
 657660.6635742188,
 674838.716796875,
 685563.7241210938,
 769862.5419921875,
 153737.35961914062,
 414117.537109375,
 40091.42395019531,
 662687.6403808594,
 30794.4375,
 28934.9775390625,
 27762.4306640625,
 25199.9658203125,
 23529.535522460938,
 25146.4140625,
 24593.709838867188,
 24418.699951171875,
 25755.63623046875,
 25831.755859375,
 26509.719116210938,
 336667.7890625,
 186304.0947265625,
 111571.82092285156,
 191085

In [119]:
np.sum(abs(chunks[448][0] - (np.ones(chunks[448][0].shape)*np.average(chunks[448][0]))))

47635.33056640625

In [110]:
np.sum(abs(chunks[16][0] - (np.ones(chunks[16][0].shape)*np.average(chunks[16][0]))))


685563.7241210938

In [112]:
np.average(chunks[16][0])

201.397705078125

In [ ]:
np.average(chunks[16][0])


In [109]:
diffs.index(np.array(diffs).max())

16

In [87]:
averages[448]

2946295

In [88]:
averages.index(averagesarray.min())

16

In [11]:
chunks[averages.index(averagesarray.max())]

(array([[186, 186, 186, ..., 185, 186, 186],
        [187, 186, 187, ..., 184, 184, 184],
        [187, 186, 187, ..., 184, 184, 184],
        ...,
        [184, 184, 183, ..., 188, 187, 187],
        [184, 184, 184, ..., 188, 187, 187],
        [183, 183, 183, ..., 188, 188, 187]], dtype=uint8),
 '27_3')

In [ ]:
cv2.imshow('Original', chunks[averages.index(averagesarray.max())][0])
cv2.waitKey(0)
cv2.destroyAllWindows()

KeyboardInterrupt: 

In [34]:

for x in range(0, len(averages)):

    cv2.imwrite(f'tile_{x}.jpg', chunks[x][0])

In [36]:
averages.index(averagesarray.max())

435

In [ ]:
cv2.imwrite('tile.jpg', chunks[averages.index(averagesarray.max())][0])

0


TypeError: list indices must be integers or slices, not numpy.float64