Image Preprocessing - Drawn Asset Creation etc.

https://markaicode.com/6-python-image-processing-libraries-for-advanced-visual-manipulation/

libs : openCV, skimage  and PIL

from skimage import io, filters, measure, segmentation
import matplotlib.pyplot as plt



In [1]:

from skimage import io, filters, measure, segmentation
import matplotlib.pyplot as plt

from PIL import Image, ImageFilter, ImageEnhance
import cv2
import numpy as np


import sys 
import os


print(sys.path)


['c:\\repos\\ComicGen\\ComicGenerator\\ComicAssets\\RawPhotos\\DrawnAssets', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311\\DLLs', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311\\Lib', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311', '', 'C:\\Users\\joshc\\AppData\\Roaming\\Python\\Python311\\site-packages', 'C:\\Users\\joshc\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32', 'C:\\Users\\joshc\\AppData\\Roaming\\Python\\Python311\\site-packages\\win32\\lib', 'C:\\Users\\joshc\\AppData\\Roaming\\Python\\Python311\\site-packages\\Pythonwin', 'c:\\Users\\joshc\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages']


In [2]:
filePaths = {}
for folder,file, dir in os.walk(os.curdir):
    directories = []
    for filepath in dir:
        directories.append(folder + f'\\{filepath}' )
    filePaths['drawn'] = directories

In [3]:
filePaths

{'drawn': ['.\\ImageProcessingDrawnAssets.ipynb',
  '.\\IMG_20260404_212428.jpg',
  '.\\IMG_20260404_225055.jpg',
  '.\\IMG_20260404_233217.jpg',
  '.\\IMG_20260405_011351.jpg',
  '.\\IMG_20260405_231047.jpg',
  '.\\IMG_20260405_231051.jpg',
  '.\\IMG_20260405_231120.jpg',
  '.\\IMG_20260405_231131.jpg',
  '.\\IMG_20260405_231135.jpg',
  '.\\IMG_20260405_231140.jpg',
  '.\\IMG_20260405_231148.jpg',
  '.\\IMG_20260405_231152.jpg',
  '.\\IMG_20260405_231216.jpg',
  '.\\IMG_20260406_025406.jpg',
  '.\\IMG_20260406_185648.jpg',
  '.\\IMG_20260406_185657.jpg',
  '.\\IMG_20260406_185700.jpg',
  '.\\IMG_20260406_185703.jpg',
  '.\\IMG_20260406_185713.jpg',
  '.\\IMG_20260406_185716.jpg',
  '.\\IMG_20260406_185719.jpg',
  '.\\IMG_20260406_185727.jpg',
  '.\\IMG_20260406_185732.jpg',
  '.\\IMG_20260406_185740.jpg',
  '.\\IMG_20260406_185759.jpg',
  '.\\IMG_20260407_193441.jpg',
  '.\\IMG_20260407_193552.jpg',
  '.\\IMG_20260407_193559.jpg',
  '.\\IMG_20260407_193604.jpg',
  '.\\IMG_20260407_193

In [4]:
testImage = cv2.imread(filePaths['drawn'][3])



In [ ]:
type(testImage)
testImage

gray_imagein = cv2.cvtColor(testImage, cv2.COLOR_BGR2GRAY) 

cv2.imshow('Original',gray_imagein)
cv2.waitKey(0)
cv2.destroyAllWindows()



array([65, 63, 64, ..., 91, 93, 91], dtype=uint8)

In [57]:
testing_logic = (gray_imagein - (np.ones(gray_imagein.shape)*255))*-1


In [58]:
testing_logic

array([[191., 193., 192., ..., 165., 163., 165.],
       [191., 191., 190., ..., 165., 163., 161.],
       [190., 190., 189., ..., 168., 168., 167.],
       ...,
       [128., 132., 134., ..., 119., 117., 113.],
       [130., 134., 134., ..., 120., 115., 111.],
       [124., 129., 135., ..., 121., 118., 117.]])

In [ ]:
gray_imagein[0]

array([64, 62, 63, ..., 90, 92, 90], dtype=uint8)

In [6]:
cv2.imshow('Original',testImage)

In [ ]:
gray_imagein[0][0]

gray_imagein.shape

(4608, 2072)

In [ ]:
gray_imagein[0:128, 0:128]

array([[64, 62, 63, ..., 71, 71, 70],
       [64, 64, 65, ..., 73, 73, 71],
       [65, 65, 66, ..., 73, 73, 71],
       ...,
       [22, 22, 20, ..., 23, 23, 19],
       [18, 19, 19, ..., 23, 22, 21],
       [18, 19, 19, ..., 19, 20, 21]], dtype=uint8)

In [ ]:
print("Image Stats")


gray_image = gray_imagein



important_Stats = []
important_Stats.append(np.average(gray_image))
important_Stats.append(np.min(gray_image))
important_Stats.append(np.max(gray_image))
important_Stats.append(np.count_nonzero(gray_image))

important_Stats


# important_Stats[0] - important_Stats[1]

print(gray_image.shape[0]/128)
print(gray_image.shape[1]/128)

iteration_step = 128
chunks = []
averages = []
diffs = []
results = []
for x in range(0, int(gray_image.shape[0]/iteration_step)):
    x_run = []

    
    
    for y in range(0, round(gray_image.shape[1]/iteration_step)):
        section = np.array(gray_image[((x)*iteration_step):(iteration_step*(x+1)), ((y)*iteration_step):iteration_step*(y+1)])
        scaled_contrast = (np.square(section / (np.ones(section.shape)*255)))*255
        contrast = abs(scaled_contrast- (np.ones(scaled_contrast.shape)*np.average(scaled_contrast)))
        
        # contrast = abs(section- (np.ones(section.shape)*np.average(section)))
        inverted =( section - (np.ones(section.shape)*255))*-1
        # averages[f'{x}_{y}'] = np.average(gray_image[((x)*iteration_step):(iteration_step*x), ((y)*iteration_step):iteration_step*y])
        chunks.append((inverted, f'{x}_{y}', section))
        averages.append(np.sum(section))
        diffs.append(np.sum(contrast))
        x_run.append(np.sum(contrast))
        
        
    results.append(x_run)
    



Image Stats
36.0
16.1875


In [126]:
np.array(results).shape

(36, 16)

In [174]:
window = 6

results = np.array(results)

id_groupings = []
centre = []

for x in range(0,results.shape[0]):
    for y in range(0,results.shape[1]):
        section = np.sum(results[max(x-(int(window/2)), 
                                     0):min(x+(int(window/2)), results.shape[0]), 
                                 max(0,y-(int(window/2))):min(results.shape[1],y+(int(window/2)))])
        
        id_groupings.append(section)
        
        centre.append(f'{x}_{y}')
        
        
        
    

In [175]:
id_groupings.index(np.array(id_groupings).max())

thresh2 = 0.65

interesting_groups = []

for x in id_groupings:
    if x > (np.array(id_groupings).max()*thresh2):
        interesting_groups.append((x, id_groupings.index(x)))

In [150]:
len(id_groupings)

576

In [176]:
len(interesting_groups)

41

In [177]:
for group, idx in interesting_groups:

    print(diffs.index(results[int(centre[idx].split("_")[0])][int(centre[idx].split("_")[1])]))

218
232
233
234
247
248
249
250
263
264
265
266
267
278
279
280
281
282
294
295
296
297
298
310
311
312
313
524
525
526
536
537
538
539
540
541
542
543
556
557
573


In [84]:
averages

[1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 1236062,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 878220,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 2249541,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1554899,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 1687891,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2557106,
 2407655,
 2407655,
 2407655,
 2407655,
 2407655,
 24076

In [116]:
averagesarray = np.array(averages)
averagesarray.max()

3043206

In [121]:
diffs.index(np.array(diffs).max())

557

In [122]:
interestingTiles = []

treshold = np.array(diffs).max()  - ((np.array(diffs).max() - np.array(diffs).min())*0.25)

i = 0
for x in diffs:
    if x > treshold:
        interestingTiles.append(i)
        
    i +=1

In [123]:
interestingTiles

[29, 30, 31, 32, 36, 557, 559, 570, 572, 573]

In [120]:
diffs

[139061.92895507812,
 271513.609375,
 320513.4279785156,
 182629.77221679688,
 206843.4835205078,
 225956.11376953125,
 236189.47790527344,
 247959.35913085938,
 260528.8292236328,
 268275.796875,
 269938.98571777344,
 276492.8037109375,
 282933.689453125,
 285343.20178222656,
 288384.38818359375,
 287656.61767578125,
 136670.1357421875,
 252808.96020507812,
 236665.2333984375,
 367101.8984375,
 151104.640625,
 454530.24853515625,
 487105.54052734375,
 516715.875,
 540910.130859375,
 562421.2277832031,
 584343.6616210938,
 614612.4145507812,
 635841.3919677734,
 657660.6635742188,
 674838.716796875,
 685563.7241210938,
 769862.5419921875,
 153737.35961914062,
 414117.537109375,
 40091.42395019531,
 662687.6403808594,
 30794.4375,
 28934.9775390625,
 27762.4306640625,
 25199.9658203125,
 23529.535522460938,
 25146.4140625,
 24593.709838867188,
 24418.699951171875,
 25755.63623046875,
 25831.755859375,
 26509.719116210938,
 336667.7890625,
 186304.0947265625,
 111571.82092285156,
 191085

In [119]:
np.sum(abs(chunks[448][0] - (np.ones(chunks[448][0].shape)*np.average(chunks[448][0]))))

47635.33056640625

In [110]:
np.sum(abs(chunks[16][0] - (np.ones(chunks[16][0].shape)*np.average(chunks[16][0]))))


685563.7241210938

In [112]:
np.average(chunks[16][0])

201.397705078125

In [ ]:
np.average(chunks[16][0])


In [109]:
diffs.index(np.array(diffs).max())

16

In [87]:
averages[448]

2946295

In [88]:
averages.index(averagesarray.min())

16

In [11]:
chunks[averages.index(averagesarray.max())]

(array([[186, 186, 186, ..., 185, 186, 186],
        [187, 186, 187, ..., 184, 184, 184],
        [187, 186, 187, ..., 184, 184, 184],
        ...,
        [184, 184, 183, ..., 188, 187, 187],
        [184, 184, 184, ..., 188, 187, 187],
        [183, 183, 183, ..., 188, 188, 187]], dtype=uint8),
 '27_3')

In [ ]:
cv2.imshow('Original', chunks[averages.index(averagesarray.max())][0])
cv2.waitKey(0)
cv2.destroyAllWindows()

KeyboardInterrupt: 

In [34]:

for x in range(0, len(averages)):

    cv2.imwrite(f'tile_{x}.jpg', chunks[x][0])

In [36]:
averages.index(averagesarray.max())

435

In [ ]:
cv2.imwrite('tile.jpg', chunks[averages.index(averagesarray.max())][0])

0


TypeError: list indices must be integers or slices, not numpy.float64